### PR TITLE
fix(SC-5540 SPT-6196): handling not iterable values on multiselect fields

### PR DESCRIPTION
**Pull request by luisduquememory**
Hi Team, this PR adds the following:

- Background conversion of not-iterable values to lists in Multiselect fields.

### CODE REVIEW

**Review by seandgrimes — CHANGES_REQUESTED** [review]
There's a couple of functional tests that are failing 

```
FAILED driver_tests/test_user_group_fields.py::TestMultiSelectUsersField::test_multi_select_users_field_single_user - Failed: DID NOT RAISE <class 'TypeError'>
FAILED driver_tests/test_user_group_fields.py::TestMultiSelectUsersField::test_multi_select_users_field_single_user_on_save - Failed: DID NOT RAISE <class 'TypeError'>
```

**Comment by luisduquememory** [comment]
> There's a couple of functional tests that are failing
> 
> ```
> FAILED driver_tests/test_user_group_fields.py::TestMultiSelectUsersField::test_multi_select_users_field_single_user - Failed: DID NOT RAISE <class 'TypeError'>
> FAILED driver_tests/test_user_group_fields.py::TestMultiSelectUsersField::test_multi_select_users_field_single_user_on_save - Failed: DID NOT RAISE <class 'TypeError'>
> ```

@seandgrimes, I’m not able to pass all the functional tests (even doing a checkout to master without any of my changes applied), I believe some of them are just broken in master, but I was able to bypass the fails you mentione. Could you please take another look?

**Comment by seandgrimes** [comment]
@luisduquememory I'm unfortunately not seeing those errors on master so I think we introduced those as part of this PR. Could you take another look? I'm still seeing them failing even with the last round of changes

**Comment by luisduquememory** [comment]
@seandgrimes, this is odd, functional tests are failing in master for me, my best bet is that this has to do with the environment used. I'll take a deep look.

**Comment by luisduquememory** [comment]
@sean, Yeah it was an environment issue, I installed a local swimlane instance and everything started working as expected. Tests are fixed now, could you please take a look?

**Review by seandgrimes — APPROVED** [review]

**Pull request merged**
